In [57]:
import pandas as pd
import numpy as np
from matplotlib import pyplot

In [32]:
!cat './master.csv' | grep ',C,08FEB2001,14FEB2001,27MAR2001' | head

,,C,08FEB2001,14FEB2001,27MAR2001,1,KSH,00077


In [3]:
df = pd.read_csv('./master.csv')
df.head()

/Users/sergeibernstein/anaconda/lib/python2.7/site-packages/pandas/io/parsers.py:1170: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  data = self._reader.read(nrows)


idncase  nat case_type c_asy_type idnproceeding base_city_code  \
0      NaN  NaN       NaN        NaN       1291207            LOS   
1      NaN  NaN       NaN        NaN       1435658            MIA   
2      NaN  NaN       NaN        NaN       3279334            HLG   
3      NaN  NaN       NaN        NaN       3279358            HOU   
4      NaN  NaN       NaN        NaN       3279361            HLG   

  hearing_loc_code dec_type dec_code other_comp   osc_date input_date  \
0              LOS      NaN      NaN          A  16AUG2004  23AUG2004   
1              MIA        O        X        NaN  16AUG2004  01OCT2004   
2              HLG        O        X        NaN  05AUG2004  31AUG2004   
3              HOU        W        X        NaN  13AUG2004  07SEP2004   
4              HLG        W        X        NaN  13AUG2004  31AUG2004   

   comp_date  attorney_flag ij_code  tracid  
0  20OCT2005              1     ATG      93  
1  04NOV2004              1     JDD     114  
2  03FEB2005              1      MB      61  
3  29OCT2004              1     MSY      69  
4  28FEB2005              1      DA      60

In [105]:
import math

def valid_asy_type(asy_type):
    if isinstance(asy_type, float) and math.isnan(asy_type):
        return True
    if isinstance(asy_type, str) and ('FEB' in asy_type or 'MAR' in asy_type):
        return False
    if asy_type in ['E', 'I', '0']:
        return True
    return True

df2 = df[df['c_asy_type'].map(valid_asy_type)]
df2 = df2[df2['ij_code'] != '1996']
df2.head(10)

idncase  nat case_type c_asy_type idnproceeding base_city_code  \
0      NaN  NaN       NaN        NaN       1291207            LOS   
1      NaN  NaN       NaN        NaN       1435658            MIA   
2      NaN  NaN       NaN        NaN       3279334            HLG   
3      NaN  NaN       NaN        NaN       3279358            HOU   
4      NaN  NaN       NaN        NaN       3279361            HLG   
5      NaN  NaN       NaN        NaN       3279363            HOU   
6      NaN  NaN       NaN        NaN       3279392            HLG   
7      NaN  NaN       NaN        NaN       3282608            HOU   
8      NaN  NaN       NaN        NaN       3299306            WAS   
9      NaN  NaN       NaN        NaN        414950            LVG   

  hearing_loc_code dec_type dec_code other_comp   osc_date input_date  \
0              LOS      NaN      NaN          A  16AUG2004  23AUG2004   
1              MIA        O        X        NaN  16AUG2004  01OCT2004   
2              HLG        O        X        NaN  05AUG2004  31AUG2004   
3              HOU        W        X        NaN  13AUG2004  07SEP2004   
4              HLG        W        X        NaN  13AUG2004  31AUG2004   
5              HOU        O        X        NaN  15AUG2004  08SEP2004   
6              HLG        W        X        NaN  19AUG2004  20SEP2004   
7              HOU      NaN      NaN        NaN  08MAY2004        NaN   
8              WAS        O        X        NaN  20AUG2004  09DEC2004   
9              LVG        O        R        NaN  19AUG2004  26AUG2004   

   comp_date  attorney_flag ij_code  tracid  
0  20OCT2005              1     ATG      93  
1  04NOV2004              1     JDD     114  
2  03FEB2005              1      MB      61  
3  29OCT2004              1     MSY      69  
4  28FEB2005              1      DA      60  
5  09FEB2005              1     MSY      69  
6  28FEB2005              1      DA      60  
7        NaN              1     JLB      66  
8  09DEC2004              1     JMB       1  
9  01FEB2005              1      IW      82

In [103]:
df2['case_type'].unique()

array([nan, 'RMV', 'AOC', 'EXC', 'DEP', 'CFR', 'REC', 'WHO', 'RFR', 'CSR',
       'CDR', '07', '01', 'NAC', '03', '02', '00', '06', '04', '2', '"',
       '1'], dtype=object)

In [104]:
df3 = df2[df2['case_type'].map(lambda x : x == '"')]
df3.head(30)

idncase nat case_type c_asy_type idnproceeding base_city_code  \
4866344  6240312  MX         "        200       4849905            ELP   
5110000  6444040  MX         "        198       5105647            ELP   
5141445  6469828  MX         "        200       5138707            ELP   
5797518  6991221  MX         "        NaN       5847932            ELP   
5963013  7118856  MX         "        NaN       6034483            ELP   
5971666  7125646  MX         "        200       6044735            ELP   

        hearing_loc_code dec_type dec_code other_comp   osc_date input_date  \
4866344              OTO        W        X        NaN  11MAR2009  15MAY2009   
5110000              EPD        O        R        NaN  01MAR2010  01MAR2010   
5141445              OTO        W        X        NaN  03MAR2010  30MAR2010   
5797518              EPD      NaN      NaN          X        NaN        NaN   
5963013              EPD        W        X        NaN  27NOV2012  03DEC2012   
5971666              EPD        W        X        NaN  13DEC2012  14DEC2012   

         comp_date  attorney_flag ij_code  tracid  
4866344  25JUN2009              1     TCR      54  
5110000  31AUG2010              1     WLA      51  
5141445  07APR2010              1     SMR     295  
5797518  10MAY2012              1     WLA      51  
5963013  14DEC2012              1     WLA      51  
5971666  27DEC2012              1     WLA      51

In [81]:
df3 = df2

nat = pd.read_csv('./tblLookupNationality.csv')
nat_keys = nat[['??','UNKNOWN COUNTRY']]
nat_keys
#nat.head()

??                    UNKNOWN COUNTRY
0    AB                              ARUBA
1    AC                ANTIGUA AND BARBUDA
2    AF                        AFGHANISTAN
3    AG                            ALGERIA
4    AL                            ALBANIA
5    AM                            ARMENIA
6    AN                            ANDORRA
7    AO                             ANGOLA
8    AR                          ARGENTINA
9    AS                          AUSTRALIA
10   AU                            AUSTRIA
11   AV                           ANGUILLA
12   AZ                         AZERBAIJAN
13   BA                            BAHRAIN
14   BB                           BARBADOS
15   BC                           BOTSWANA
16   BD                            BERMUDA
17   BE                            BELGIUM
18   BF                            BAHAMAS
19   BG                         BANGLADESH
20   BH                             BELIZE
21   BI                 BOSNIA-HERZEGOVINA
22   BL                            BOLIVIA
23   BM                    BURMA (MYANMAR)
24   BN                              BENIN
25   BO                       BURKINA FASO
26   BP                    SOLOMON ISLANDS
27   BR                             BRAZIL
28   BS              BYELORUSSIA (BELARUS)
29   BT                             BHUTAN
..   ..                                ...
217  TO                               TOGO
218  TP              SAO TOME AND PRINCIPE
219  TR                       TURKMENISTAN
220  TS                            TUNISIA
221  TU                             TURKEY
222  TV                             TUVALU
223  TW                             TAIWAN
224  TZ                           TANZANIA
225  UE                            UKRAINE
226  UG                             UGANDA
227  UK                     UNITED KINGDOM
228  UR                       SOVIET UNION
229  UV                        UPPER VOLTA
230  UY                            URUGUAY
231  UZ                        UZEBEKISTAN
232  VC     ST. VINCENT AND THE GRENADINES
233  VE                          VENEZUELA
234  VI             BRITISH VIRGIN ISLANDS
235  VM                            VIETNAM
236  WA                            NAMIBIA
237  WI                     WESTERN SAHARA
238  WS                              SAMOA
239  WZ                          SWAZILAND
240  XS                        SOUTH SUDAN
241  XX  BE REMOVED FROM THE UNITED STATES
242  YE                              YEMEN
243  YO                         YUGOSLAVIA
244  YS                  SERBIA MONTENEGRO
245  ZA                             ZAMBIA
246  ZI                           ZIMBABWE

[247 rows x 2 columns]

In [70]:
df3['nat'].unique()

array([nan, '??', 'WQ', 'CQ', 'US', 'NQ', 'MS', 'IY', 'GQ', 'AQ', 'VO',
       'RQ', 'PG', '23', '27', 'PF', 'JS', 'BQ', '70', 'WF', 'NX', 'DU',
       'ND'], dtype=object)

In [84]:
df2['ij_code'].unique()

array(['ATG', 'JDD', 'MB', 'MSY', 'DA', 'JLB', 'JMB', 'IW', '1996', 'RDV',
       'JLG', 'CC', 'GPK', 'CMZ', 'EAL', 'WI', 'AO', 'TC', 'HJS', 'EP',
       'OJB', 'PMG', 'BLF', 'CHC', 'JRF', 'KJ', 'TMO', 'WLA', 'MWS', 'WAC',
       'PDF', 'RRO', 'JDP', 'VJ1', 'IJ6', 'CEP', 'WCP', 'HEA', 'PSL',
       'ERH', 'RHK', 'WVW', 'ASG', 'CLR', 'JAD', 'ET', 'AJR', 'DBS', 'HR',
       'KSH', 'JVC', 'SY', 'BAN', 'GCV', 'DAR', 'WFN', 'WLN', 'IEB', 'HSD',
       'RJD', 'PPL', 'LRD', 'RTG', 'WAH', 'JCW', 'GMR', 'PAM', 'GTG',
       'DLK', 'SLS', 'ADP', 'ECC', 'JWR', 'MAK', 'MMT', 'RGS', 'RBR',
       'PAR', 'RDW', 'JTZ', 'AMC', 'JPV', 'LJM', 'HGW', 'SJM', 'AAV',
       'ACB', 'JMS', 'WEW', 'BWD', 'BJE', 'MFS', 'GPM', 'DAM', 'BMB',
       'TMR', 'RFB', 'BHS', 'BQM', 'GA', 'GDB', 'XXX', 'JFG', 'JKS', 'DRJ',
       'RJB', 'BJH', 'MHB', 'GGD', 'LND', 'SHK', 'RS', 'JWS', 'CJS', 'RLM',
       'JZ', 'SMJ', 'BAZ', 'LSF', nan, 'PS', 'KAB', 'PLJ', 'WFJ', 'WAD',
       'RKM', 'GZM', 'IS', 'PMS', 'JDM', 'CMH', 'PG

In [4]:
df.describe()

idncase  attorney_flag          tracid
count  6084423.000000        3039846  5742523.000000
mean   4578281.989466              1      145.150340
std    1545765.205544              0       98.732414
min    2046920.000000              1        1.000000
25%    3218485.000000              1       59.000000
50%    4382067.000000              1      138.000000
75%    5987178.500000              1      211.000000
max    7218474.000000              1      403.000000

In [19]:
h = pd.read_csv('./master_case_type.csv')
h['strCode'].unique()

array(['AOC', 'CDR', 'CFR', 'CSR', 'DCC', 'DDC', 'DEP', 'EXC', 'NAC',
       'REC', 'RFR', 'RMV', 'WHO'], dtype=object)

In [ ]:
# Undefined nat values
# array([nan, '??', 'WQ', 'CQ', 'US', 'NQ', 'MS', 'IY', 'GQ', 'AQ', 'VO',
#       'RQ', 'PG', '23', '27', 'PF', 'JS', 'BQ', '70', 'WF', 'NX', 'DU',
#       'ND'], dtype=object)
#
#
#